### ISSUE TITLE
Polling too often.

### ISSUE THREAD

**Issue by mike-s123** [BugerDread/esp8266-ezTIME-wifi-clock#1]
Your code is polling a pool.ntp.org time server every 10 minutes. That is a violation of their Terms of Service ( https://www.ntppool.org/tos.html ). 

The ezTime library operates as an SNTP client, which shall not "Request time from the Services more than once every thirty (30) minutes" or "Set up a regular time sync interval such as ... “at minute or second X”." 

I suggest adding `setInterval(1801);` to resolve the issue.

**Comment by BugerDread** [comment]
my code is not changing the default pooling interval of eztime library, which is already set to 1801

https://github.com/ropg/ezTime/blob/7b3c8aa020be818ac149e0762543ac5e81ccfabe/src/ezTime.h#L149
